setwd("/Users/matiaszenklusen/Documents/Master's thesis/R scripts")
library(icosa)
library(sf)
library(terra)
library(raster)
library(sp)

#Zoolithenhöhle location (earth)
ne <- sf::st_read("ne_10m_land/ne_10m_land.shx")
countries <- sf::st_read("1_vectors-2/data/world_admin/world-administrative-boundaries.shx")
quartz()
plot(ne$geometry)
dir.create("export", showWarnings=FALSE)
png("export/worldmap.png", height=1000, width=2000)
plot(ne$geometry)
dev.off()
plot(ne$geometry, col="lightblue", border="black", xlim=c(30, 45), ylim=c(35,80))
plot(countries$geometry,add=TRUE)
Zoolithenhöhle <- c(11.28, 49.78)
Kudaro<-c(42.31, 43.38)
Scladina<-c(5.1,50.29)
points(Zoolithenhöhle[1],Zoolithenhöhle[2])
points(Kudaro[1],Kudaro[2])
points(Scladina[1],Scladina[2])
