setwd("/Users/matiaszenklusen/Documents/Master's thesis/R scripts")
library(icosa)
library(sf)
library(terra)
library(raster)
library(sp)

#Zoolithenhöhle location (earth)
ne <- sf::st_read("ne_10m_land/ne_10m_land.shx")
quartz()
plot(ne$geometry)
dir.create("export", showWarnings=FALSE)
png("export/worldmap.png", height=1000, width=2000)
plot(ne$geometry)
dev.off()
plot(ne$geometry, col="lightblue", border="black", xlim=c(-90, 90), ylim=c(-90,90))
Zoolithenhöhle <- c(11.28, 49.78)
points(Zoolithenhöhle[1],Zoolithenhöhle[2])

#Zoolithenhöhle location (Germany)
countries <- sf::st_read("1_vectors-2/data/world_admin/world-administrative-boundaries.shx")
plot(countries$geometry,add=TRUE)
germany <- countries[which(countries$name=="Germany"), ]
plot(germany$geometry)
plot(germany$geometry, col="lightblue", border="black")
points(Zoolithenhöhle[1],Zoolithenhöhle[2])
dev.off()
